part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const CART = _Paths.CART;
  static const PROFILE = _Paths.PROFILE;
  static const PRODUCT_DETAILS = _Paths.PRODUCT_DETAILS;
  static const MAIN = _Paths.MAIN;
  static const SEARCH = _Paths.SEARCH;
  static const PRODUCTS = _Paths.PRODUCTS;
  static const ORDERS = _Paths.ORDERS;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const ADDRESS = _Paths.ADDRESS;
  static const HELP_SUPPORT = _Paths.HELP_SUPPORT;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const NOTIFICATIONS_SETTING = _Paths.NOTIFICATIONS_SETTING;
  static const VENDERS = _Paths.VENDERS;
  static const AUTH = _Paths.AUTH;
  static const VENDERS_ORDER_DETAIL = _Paths.VENDERS_ORDER_DETAIL;
  static const VENDERS_ORDERS = _Paths.VENDERS_ORDERS;
  static const VENDERS_DASHBOARD = _Paths.VENDERS_DASHBOARD;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const VERNDORS_COMPANY_SELECTION = _Paths.VERNDORS_COMPANY_SELECTION;
  static const VERNDORS_CATEGORY_SELECTION = _Paths.VERNDORS_CATEGORY_SELECTION;
  static const CATEGORIES = _Paths.CATEGORIES;
  static const SPLASH = _Paths.SPLASH;
  static const VENDORS_PROFILE = _Paths.VENDORS_PROFILE;
  static const VENDORS_PORDUCTS = _Paths.VENDORS_PORDUCTS;
  static const KESHAV = _Paths.KESHAV;
  static const CHECKOUT = _Paths.CHECKOUT;
  static const ORDER_SUCCESS = _Paths.ORDER_SUCCESS;
  static const BUSSINESS_DITAILS = _Paths.BUSSINESS_DITAILS;
  static const SUBSCRIPTION = _Paths.SUBSCRIPTION;
  static const VENDORS_LIST_VIEW = _Paths.VENDORS_LIST_VIEW;
  static const VENDOR_PRODUCT_STORE = _Paths.VENDOR_PRODUCT_STORE;
  static const PHONE_LOGIN = _Paths.PHONE_LOGIN;
  static const OFFLINE = _Paths.OFFLINE;
  static const COMPANIES_LIST = _Paths.COMPANIES_LIST;
  static const COMPANY_DIVISION = _Paths.COMPANY_DIVISION;
  static const COMPANY_DIVISION_SELECTION = _Paths.COMPANY_DIVISION_SELECTION;
  static const BUYER_FAV_AGENCY_SELECTION = _Paths.BUYER_FAV_AGENCY_SELECTION;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const CART = '/cart';
  static const PROFILE = '/profile';
  static const PRODUCT_DETAILS = '/product-details/:id';
  static const MAIN = '/main';
  static const SEARCH = '/search';
  static const PRODUCTS = '/vendors_products';
  static const ORDERS = '/orders';
  static const EDIT_PROFILE = '/edit-profile';
  static const ADDRESS = '/address';
  static const HELP_SUPPORT = '/help-support';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const NOTIFICATIONS = '/notifications';
  static const NOTIFICATIONS_SETTING = '/notifications-setting';
  static const VENDERS = '/venders';
  static const AUTH = '/auth';
  static const VENDERS_ORDER_DETAIL = '/venders-order-details';
  static const VENDERS_DASHBOARD = '/venders-dashboard';
  static const VENDERS_ORDERS = '/venders-orders';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const VERNDORS_COMPANY_SELECTION = '/vendors-company-selection';
  static const VERNDORS_CATEGORY_SELECTION = '/vendors-category-selection';
  static const CATEGORIES = '/categories';
  static const SPLASH = '/splash';
  static const VENDORS_PROFILE = '/vendors-profile';
  static const VENDORS_PORDUCTS = '/vendors-products';
  static const KESHAV = '/keshav';
  static const CHECKOUT = '/checkout';
  static const ORDER_SUCCESS = '/order-success';
  static const BUSSINESS_DITAILS = '/bussiness-ditails';
  static const SUBSCRIPTION = '/subscription';
  static const VENDORS_LIST_VIEW = '/vendors-list-view';
  static const VENDOR_PRODUCT_STORE = '/vendor-product-store';
  static const PHONE_LOGIN = '/phone-login';
  static const OFFLINE = '/offline';
  static const COMPANIES_LIST = '/companies-list';
  static const COMPANY_DIVISION = '/company-division';
  static const COMPANY_DIVISION_SELECTION = '/company-division-selection';
  static const BUYER_FAV_AGENCY_SELECTION = '/buyer-fav-agency-selection';
}
